import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [11]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
sns.set(style='whitegrid')

Matplotlib is building the font cache; this may take a moment.

In [14]:
import os

os.listdir('.')

['.idea',
 '.venv',
 '2019-Nov.csv',
 '2019-Oct.csv',
 'data',
 'models',
 'README.md',
 'requirements.txt',
 'sample.ipynb']

In [24]:
df_oct = pd.read_csv('2019-Oct.csv', nrows=500000)

df_nov = pd.read_csv('2019-Nov.csv', nrows=500000)

df = pd.concat([df_oct, df_nov], ignore_index=True)

In [25]:
df.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d
5,2019-10-01 00:00:05 UTC,view,1480613,2053013561092866779,computers.desktop,pulser,908.62,512742880,0d0d91c2-c9c2-4e81-90a5-86594dec0db9
6,2019-10-01 00:00:08 UTC,view,17300353,2053013553853497655,NaN,creed,380.96,555447699,4fe811e9-91de-46da-90c3-bbd87ed3a65d
7,2019-10-01 00:00:08 UTC,view,31500053,2053013558031024687,NaN,luminarc,41.16,550978835,6280d577-25c8-4147-99a7-abc6048498d6
8,2019-10-01 00:00:10 UTC,view,28719074,2053013565480109009,apparel.shoes.keds,baden,102.71,520571932,ac1cd4e5-a3ce-4224-a2d7-ff660a105880
9,2019-10-01 00:00:11 UTC,view,1004545,2053013555631882655,electronics.smartphone,huawei,566.01,537918940,406c46ed-90a4-4787-a43b-59a410c1a5fb

In [26]:
df.info

<bound method DataFrame.info of                      event_time event_type  product_id          category_id  \
0       2019-10-01 00:00:00 UTC       view    44600062  2103807459595387724
1       2019-10-01 00:00:00 UTC       view     3900821  2053013552326770905
2       2019-10-01 00:00:01 UTC       view    17200506  2053013559792632471
3       2019-10-01 00:00:01 UTC       view     1307067  2053013558920217191
4       2019-10-01 00:00:04 UTC       view     1004237  2053013555631882655
...                         ...        ...         ...                  ...
999995  2019-11-01 09:18:16 UTC       view    21408811  2053013561579406073
999996  2019-11-01 09:18:16 UTC       view    26300509  2053013563424899933
999997  2019-11-01 09:18:17 UTC       view    10800074  2053013554994348409
999998  2019-11-01 09:18:17 UTC       view     1005116  2053013555631882655
999999  2019-11-01 09:18:17 UTC       view     1801623  2053013554415534427

                              category_code     brand    price    user_id  \
0                                       NaN  shiseido    35.79  541312140
1       appliances.environment.water_heater      aqua    33.20  554748717
2                furniture.living_room.sofa       NaN   543.10  519107250
3                        computers.notebook    lenovo   251.74  550050854
4                    electronics.smartphone     apple  1081.98  535871217
...                                     ...       ...      ...        ...
999995                   electronics.clocks    orient   122.01  513642258
999996                                  NaN       NaN   925.71  514231939
999997                                  NaN   redmond    36.01  519989010
999998               electronics.smartphone     apple  1010.85  519941953
999999                 electronics.video.tv        lg   385.85  526099873

                                user_session
0       72d76fde-8bb3-4e00-8c23-a032dfed738c
1       9333dfbd-b87a-4708-9857-6336556b0fcc
2       566511c2-e2e3-422b-b695-cf8e6e792ca8
3       7c90fc70-0e80-4590-96f3-13c02c18c713
4       c6bd7419-2748-4c56-95b4-8cec9ff8b80d
...                                      ...
999995  b937e894-de33-4127-956a-edc6354aabd8
999996  da671345-0db9-432a-9942-f2076f06d146
999997  7e5803a3-c2a4-4a34-b72d-302318cafcd7
999998  579ba541-20c3-49c7-8402-961432fc3f54
999999  9586d366-37f0-49db-9734-194de834b9c1

[1000000 rows x 9 columns]>

In [27]:
print(df.columns.tolist())

['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

In [28]:
missing_values = df.isnull().sum()
print(missing_values)

event_time            0
event_type            0
product_id            0
category_id           0
category_code    320811
brand            146642
price                 0
user_id               0
user_session          0
dtype: int64

In [29]:
df = df.drop_duplicates()

In [30]:
df.isnull()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,True,True,False,False,False
999997,False,False,False,False,True,False,False,False,False
999998,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

event_time            0
event_type            0
product_id            0
category_id           0
category_code    320703
brand            146627
price                 0
user_id               0
user_session          0
dtype: int64